.TH "WS1" 3 "Sun Jan 11 2015" "ws1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WS1 \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Represents an activity of webservice 1
.PP
public 
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org
.RE
.PP
Represents an user of webservice 1
.PP
public 
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org
.RE
.PP
include \fBWS1_user\fP
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org include nusoap library
.PP
firstname and lastname of author, author@example.org include our library with some DB functions
.PP
firstname and lastname of author, author@example.org Short description of class \fBWS1_webservice\fP
.RE
.PP
public 
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ws1 from the source code\&.
