.TH "C:/Users/Alessandro/Desktop/ES-Project/WS2/lib Directory Reference" 3 "Sun Jan 11 2015" "ws2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Alessandro/Desktop/ES-Project/WS2/lib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfunctions\&.php\fP"
.br
.in -1c
