.TH "WS2" 3 "Sun Jan 11 2015" "ws2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WS2 \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
include \fBWS2_PacientInfo\fP
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org link a given caretaker to a pacient activity into the database
.RE
.PP
public 
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org
.RE
.PP
Short description of class \fBWS2_Caretaker\fP
.PP
public 
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org
.RE
.PP
Short description of class \fBWS2_Pacient\fP
.PP
public 
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org
.RE
.PP
stores an the url of an activity of a pacient
.PP
public 
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org
.RE
.PP
a generic user for the webservice 2
.PP
public 
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org
.RE
.PP
include \fBWS2_Pacient\fP
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org include \fBWS2_PacientInfo\fP
.PP
firstname and lastname of author, author@example.org Short description of class \fBWS2_Webservice\fP
.RE
.PP
public 
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ws2 from the source code\&.
