.TH "WS2_User" 3 "Sun Jan 11 2015" "ws2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WS2_User \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBWS2_Caretaker\fP, and \fBWS2_Pacient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetFirstname\fP ()"
.br
.ti -1c
.RI "\fBgetLastname\fP ()"
.br
.ti -1c
.RI "\fBgetUsername\fP ()"
.br
.ti -1c
.RI "\fBgetBirthdate\fP ()"
.br
.ti -1c
.RI "\fBgetGender\fP ()"
.br
.ti -1c
.RI "\fBgetToken\fP ()"
.br
.ti -1c
.RI "\fBsetToken\fP ($token)"
.br
.ti -1c
.RI "\fB__construct\fP ($firstname, $lastname, $username, $birthdate, $gender)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ($firstname, $lastname, $username, $birthdate, $gender)"
constructor for a \fBWS2_User\fP
.PP
public 
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIString\fP firstname 
.br
\fIString\fP lastname 
.br
\fIString\fP username 
.br
\fIString\fP birthdate 
.br
\fIchar\fP gender 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ws2 from the source code\&.
