.TH "WS2_Pacient" 3 "Sun Jan 11 2015" "ws2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WS2_Pacient \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWS2_User\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetFirstname\fP ()"
.br
.ti -1c
.RI "\fBgetLastname\fP ()"
.br
.ti -1c
.RI "\fBgetUsername\fP ()"
.br
.ti -1c
.RI "\fBgetBirthdate\fP ()"
.br
.ti -1c
.RI "\fBgetGender\fP ()"
.br
.ti -1c
.RI "\fBgetToken\fP ()"
.br
.ti -1c
.RI "\fBregisterPacient\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBexistPacient\fP ($pacient)"
.br
.ti -1c
.RI "static \fBvalidatePacient\fP ($pacient, $token)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static existPacient ($pacient)\fC [static]\fP"
check if a given pacient is in the database
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIString\fP pacient return boolean 
.RE
.PP

.SS "registerPacient ()"
register a pacient into the ws2 database
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org return String 
.RE
.PP

.SS "static validatePacient ($pacient, $token)\fC [static]\fP"
check if a token is valid for a given pacient
.PP
\fBAuthor:\fP
.RS 4
firstname and lastname of author, author@example.org 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIString\fP username return boolean 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ws2 from the source code\&.
